# Generated by Django 6.0.5 on 2026-05-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='plan_h',
            field=models.FloatField(default=14, help_text='Height on floor plan (0–100%).'),
        ),
        migrations.AddField(
            model_name='table',
            name='plan_w',
            field=models.FloatField(default=12, help_text='Width on floor plan (0–100%).'),
        ),
        migrations.AddField(
            model_name='table',
            name='plan_x',
            field=models.FloatField(blank=True, help_text='Horizontal position on floor plan (0–100%).', null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='plan_y',
            field=models.FloatField(blank=True, help_text='Vertical position on floor plan (0–100%).', null=True),
        ),
    ]
