# Generated by Django 6.0.5 on 2026-05-23 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_table_plan_h_table_plan_w_table_plan_x_table_plan_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#2DB5A3', max_length=7),
        ),
        migrations.CreateModel(
            name='CompanyLegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_name_el', models.CharField(blank=True, max_length=255)),
                ('trade_name_en', models.CharField(blank=True, max_length=255)),
                ('address_el', models.TextField(blank=True)),
                ('address_en', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('gemi_number', models.CharField(blank=True, help_text='Γ.Ε.ΜΗ. — optional but recommended for digital menus.', max_length=50, verbose_name='GEMI number')),
                ('consumer_payment_notice_el', models.TextField(default='Ο ΚΑΤΑΝΑΛΩΤΗΣ ΔΕΝ ΕΧΕΙ ΥΠΟΧΡΕΩΣΗ ΝΑ ΠΛΗΡΩΣΕΙ ΕΑΝ ΔΕΝ ΛΑΒΕΙ ΤΟ ΝΟΜΙΜΟ ΠΑΡΑΣΤΑΤΙΚΟ ΣΤΟΙΧΕΙΟ (ΑΠΟΔΕΙΞΗ-ΤΙΜΟΛΟΓΙΟ)')),
                ('consumer_payment_notice_en', models.TextField(default='CONSUMER IS NOT OBLIGED TO PAY IF THE NOTICE OF PAYMENT (RECEIPT-INVOICE) HAS NOT BEEN RECEIVED')),
                ('complaint_sheets_notice_el', models.TextField(default='Το κατάστημα διαθέτει εγκεκριμένα έντυπα δελτία για την καταγραφή τυχόν παραπόνων')),
                ('complaint_sheets_notice_en', models.TextField(default='The shop is equipped with official sheets for any complaint')),
                ('prices_include_taxes_el', models.TextField(default='Στις τιμές συμπεριλαμβάνονται όλες οι νόμιμες επιβαρύνσεις (Φ.Π.Α. και Δημοτικός Φόρος)')),
                ('prices_include_taxes_en', models.TextField(default='All prices include applicable taxes (VAT and municipal tax)')),
                ('service_charge_enabled', models.BooleanField(default=False)),
                ('service_charge_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Explicit cover/service charge in € (if applicable).', max_digits=8, null=True)),
                ('service_charge_note_el', models.TextField(blank=True, default='Χρέωση κουβέρ / service charge: αναφέρεται ξεχωριστά. Το ψωμί και το νερό χρεώνονται μόνο αν τα ζητήσει ο πελάτης.')),
                ('service_charge_note_en', models.TextField(blank=True, default='Cover / service charge is shown separately. Bread and water are charged only if requested.')),
                ('allergen_notice_el', models.TextField(blank=True, default='Ενημέρωση για αλλεργιογόνα σύμφωνα με τον Κανονισμό (ΕΕ) 1169/2011. Τα σύμβολα δίπλα σε κάθε πιάτο αναφέρουν τις 14 βασικές αλλεργιογόνες ουσίες.')),
                ('allergen_notice_en', models.TextField(blank=True, default='Allergen information pursuant to Regulation (EU) No 1169/2011. Icons next to each dish indicate the 14 major allergen groups.')),
                ('product_legend_el', models.TextField(blank=True, default='* Κατεψυγμένο προϊόν · Ελαιόλαδο/σπορέλαιο/έξτρα παρθένο όπου αναφέρεται · Προέλευση/Π.Ο.Π. όπου αναφέρεται στο πιάτο.')),
                ('product_legend_en', models.TextField(blank=True, default='* Frozen product · Olive/seed/extra virgin olive oil as stated · Origin / PDO (P.O.P.) as stated on the dish.')),
                ('show_on_guest_menu', models.BooleanField(default=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'company legal profile',
                'verbose_name_plural': 'company legal profiles',
            },
        ),
    ]
