# Generated by Django 6.0.5 on 2026-05-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_primary_color_companylegalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylegalprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown on guest QR menus with company details (not the Baresto app logo).', upload_to='restaurants/company_logos/'),
        ),
    ]
