# Generated by Django 6.0.5 on 2026-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('waiter', 'Waiter'), ('cashier', 'Cashier'), ('kitchen', 'Kitchen')], default='waiter', max_length=20)),
                ('pin', models.CharField(blank=True, max_length=6)),
                ('avatar', models.ImageField(blank=True, upload_to='staff/avatars/')),
                ('is_active_shift', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
