# Generated by Django 6.0.5 on 2026-05-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_allergen_name_el_allergen_name_en_menu_name_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Mandatory label for dishes with frozen meat, fish or seafood.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='oil_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('olive', 'Olive oil'), ('seed', 'Seed oil (e.g. sunflower)'), ('ev_olive', 'Extra virgin olive oil')], max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='origin_note_el',
            field=models.CharField(blank=True, help_text='Meat/seafood origin or PDO name (e.g. Φέτα Π.Ο.Π.).', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='origin_note_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
